import { NextRequest, NextResponse } from 'next/server'
import { createServiceClient } from '@/lib/supabase/server'
import jwt from 'jsonwebtoken'
import { FRANCHISES } from '@/lib/utils/constants'
import type { RoomSettings, FranchiseCode } from '@/types'

// ---- Auth helper ----
function getCallerFromRequest(req: NextRequest) {
  const token = req.cookies.get('ipl_token')?.value
  if (!token) return null
  try {
    return jwt.verify(token, process.env.JWT_SECRET!) as { id: string; role: string; franchise: string }
  } catch { return null }
}

// ============================================================
// GET /api/rooms — list active public rooms
// ============================================================
export async function GET(req: NextRequest) {
  const caller = getCallerFromRequest(req)
  if (!caller) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const supabase = createServiceClient()
  const { data, error } = await supabase
    .from('rooms')
    .select(`
      id, code, name, status, access_type, created_at,
      room_members(count)
    `)
    .in('status', ['waiting', 'retention', 'auction'])
    .eq('access_type', 'public')
    .order('created_at', { ascending: false })

  if (error) return NextResponse.json({ error: 'Failed to fetch rooms' }, { status: 500 })
  return NextResponse.json({ rooms: data })
}

// ============================================================
// POST /api/rooms — create a new room
// ============================================================
export async function POST(req: NextRequest) {
  const caller = getCallerFromRequest(req)
  if (!caller) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  // Only auctioneer, curator, super_admin can create rooms
  if (!['auctioneer', 'curator', 'super_admin'].includes(caller.role)) {
    return NextResponse.json({ error: 'Only auctioneers can create rooms' }, { status: 403 })
  }

  const body = await req.json()
  const {
    name,
    access_type = 'code',
    db_source   = 'global',
    settings    = {},
    is_tournament = false,
    franchise_overrides = {},
  } = body

  if (!name?.trim()) return NextResponse.json({ error: 'Room name required' }, { status: 400 })

  const supabase = createServiceClient()

  const defaultSettings: RoomSettings = {
    budget_cr:           120,
    max_squad:           25,
    max_overseas:        4,
    max_retentions:      3,
    rtm_per_team:        1,
    emergency_loan_cr:   10,
    auction_speed:       'normal',
    timer_seconds:       10,
    min_wk:              1,
    min_bowlers:         3,
    min_overseas:        2,
    min_squad_size:      15,
    price_drop_on_no_bid: true,
    price_drop_pct:      10,
    secret_budget:       false,
    dynasty_mode:        false,
    tier_order:          ['Icon', 'Platinum', 'Gold', 'Silver', 'Bronze'],
    ...settings,
  }

  // Create room (code auto-generated by DB trigger)
  const { data: room, error: roomError } = await supabase
    .from('rooms')
    .insert({
      name:         name.trim(),
      host_id:      caller.id,
      access_type,
      db_source,
      settings:     defaultSettings,
      is_tournament,
    })
    .select()
    .single()

  if (roomError || !room) {
    return NextResponse.json({ error: 'Failed to create room' }, { status: 500 })
  }

  // Generate invite link if access_type is 'link'
  if (access_type === 'link') {
    const token   = crypto.randomUUID()
    const link    = `${process.env.NEXT_PUBLIC_APP_URL}/join/${token}`
    await supabase.from('rooms').update({ invite_link: link }).eq('id', room.id)
    room.invite_link = link
  }

  // Add host as auctioneer member
  const hostFranchise = (caller.franchise as FranchiseCode) ?? 'MI'
  await supabase.from('room_members').insert({
    room_id:          room.id,
    user_id:          caller.id,
    franchise:        hostFranchise,
    role:             'auctioneer',
    budget_remaining: defaultSettings.budget_cr,
  })

  // Auto-fill remaining slots with bots for available franchises
  const takenFranchises = new Set([hostFranchise])
  const allFranchises   = Object.keys(FRANCHISES) as FranchiseCode[]
  const botSlots        = allFranchises.filter(f => !takenFranchises.has(f))

  const botInserts = botSlots.map(franchise => {
    const f = FRANCHISES[franchise]
    return {
      room_id:          room.id,
      franchise,
      role:             'team_owner' as const,
      is_bot:           true,
      budget_remaining: defaultSettings.budget_cr,
      bot_personality:  {
        aggression:     franchise_overrides[franchise]?.aggression ?? f.aggression,
        max_multiplier: franchise_overrides[franchise]?.max_multiplier ?? f.max_multiplier,
        preferred_role: franchise_overrides[franchise]?.preferred_role ?? f.preferred_role,
      },
    }
  })

  if (botInserts.length) {
    await supabase.from('room_members').insert(botInserts)
  }

  // Add players to room based on db_source
  if (db_source === 'global') {
    const { data: players } = await supabase
      .from('players')
      .select('id, stock_tier')
      .eq('is_active', true)
      .eq('is_custom', false)

    if (players?.length) {
      // Order by tier, then shuffle within tier
      const tierOrder = defaultSettings.tier_order
      const grouped   = tierOrder.reduce((acc, tier) => {
        acc[tier] = players.filter(p => p.stock_tier === tier)
        return acc
      }, {} as Record<string, typeof players>)

      let order = 0
      let set   = 1
      const roomPlayers = []

      for (const tier of tierOrder) {
        const tierPlayers = grouped[tier] ?? []
        // Shuffle within tier
        tierPlayers.sort(() => Math.random() - 0.5)

        for (const player of tierPlayers) {
          roomPlayers.push({
            room_id:      room.id,
            player_id:    player.id,
            set_number:   set,
            reveal_order: order++,
            status:       'pending',
          })
          // New set every 25 players
          if (order % 25 === 0) set++
        }
      }

      await supabase.from('room_players').insert(roomPlayers)
    }
  }

  // Audit log
  await supabase.from('audit_logs').insert({
    admin_id:   caller.id,
    admin_name: caller.id,
    action:     'room_created',
    target:     room.id,
    level:      'info',
    meta:       { name: room.name, access_type, code: room.code },
  })

  return NextResponse.json({ room }, { status: 201 })
}
